REGEX_ALPHANUMERIC_WITH_DOTS = /\A[a-zA-Z0-9.-]+\z/
REGEX_BUSINESS_NAME = /\A[A-Za-zÀ-ÿ0-9\-.\s]+\z/
REGEX_DOCUMENTATION = %r{\A[0-9.\-/]+\z}
REGEX_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
REGEX_FULL_NAME = /\A[A-Za-zÀ-ÿ\s]+\z/
REGEX_NUMBER_WITH_DOTS = /\A[0-9\-.]+\z/
REGEX_NUMBERS_ONLY = /\A[0-9]+\z/
REGEX_PHONE_NUMBER = /\A\(\d{2}\) 9?\d{4}-\d{4}\z/
REGEX_REFERENCE_CODE = /\A[A-Z0-9-]+\z/
REGEX_STATE_CODE = /\A[A-Z]+\z/
REGEX_UUID = /\A[a-zA-Z0-9\-]+\z/
REGEX_URL = /\Ahttps?:\/\/[^\s\/$.?#].[^\s]*\z/i
