### List Accounts

GET {{host}}/v1/accounts?limit=10 HTTP/1.1
content-type: application/json

### Show Account

GET {{host}}/v1/accounts/1 HTTP/1.1
content-type: application/json

### Create Account

POST {{host}}/v1/accounts HTTP/1.1
content-type: application/json

{
  "provider_account_id": 1,
  "description": "Sacador Cobrancas S.A",
  "document_type": "CPF",
  "document_number": "404.782.851-32",
  "credentials": "{\"appKey\":\"A001\",\"clientId\":\"1234\",\"clientSecret\":\"abc1234\"}"
}

### Update Account

PATCH {{host}}/v1/accounts/1 HTTP/1.1
content-type: application/json

{
  "description": "Sacador Cobrancas S.A",
  "document_type": "CPF",
  "document_number": "123.456.789-09"
}

### Delete Account

DELETE {{host}}/v1/accounts/2 HTTP/1.1
content-type: application/json
