### List Accounts

GET http://localhost:3000/v1/accounts?limit=10 HTTP/1.1
content-type: application/json

### Show Account

GET http://localhost:3000/v1/accounts/1 HTTP/1.1
content-type: application/json

### Create Account

POST http://localhost:3000/v1/accounts HTTP/1.1
content-type: application/json

{
  "provider_account_id": 1,
  "description": "Sacador Cobrancas S.A",
  "document_type": "CPF",
  "document_number": "123.456.789-09",
  "credentials": "{\"appKey\":\"A001\",\"clientId\":\"1234\",\"clientSecret\":\"abc1234\"}"
}

### Update Account

PATCH http://localhost:3000/v1/accounts/1 HTTP/1.1
content-type: application/json

{
  "description": "Sacador Cobrancas S.A",
  "document_type": "CPF",
  "document_number": "123.456.789-09"
}

### Delete Account

DELETE http://localhost:3000/v1/accounts/2 HTTP/1.1
content-type: application/json
