### Create Boleto

POST http://localhost:3000/v1/boletos HTTP/1.1
content-type: application/json
X-Account-Id: 1

{
  "covenant_id": "001-123456-10",
  "our_number": "1234591",
  "reference_code": "123567",
  "issuing_bank": "BANCO_BRASIL",
  "issue_data": {
    "modality_code": "1",
    "wallet_number": "17",
    "agreement_number": "3128557",
    "wallet_variation_number": "35"
  },
  "issue_date": "2024-02-09",
  "due_date": "2024-09-20",
  "amount": "100.00",
  "discount_amount": "0",
  "fine_amount": "0",
  "interest_amount": "0",
  "boleto_type_code": 1,
  "boleto_type_description": "Duplicata Mercantil",
  "beneficiary_type": "CNPJ",
  "beneficiary_document": "90.890.230/0001-66",
  "beneficiary_name": "Sacador Cobrancas S.A",
  "payer_type": "CPF",
  "payer_document": "863.829.147-70",
  "payer_name": "Jose da Silva",
  "payer_address": "Rua das Flores",
  "payer_address_number": "123",
  "payer_zip_code": "14340-000",
  "payer_city": "Brodowski",
  "payer_neighborhood": "Centro",
  "payer_state": "SP",
  "payer_phone": "(11) 91234-0192"
}

### Boleto Register

GET http://localhost:3000/v1/boletos/1/register HTTP/1.1
content-type: application/json
account-id: 1
