default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL", "mysql2://root@localhost/banking_gateway_development") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
