default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  primary: &primary_development
    <<: *default
    database: banking_gateway_development
  cache:
    <<: *primary_development
    migrations_paths: db/cache_migrate

test:
  <<: *default
  database: banking_gateway_test

production:
  primary: &primary_production
    <<: *default
    database: banking_gateway_production
    username: banking_gateway
    password: <%= ENV["BANKING_GATEWAY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: banking_gateway_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: banking_gateway_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: banking_gateway_production_cable
    migrations_paths: db/cable_migrate
